### ISSUE TITLE
Error: dns service error: unknown

### ISSUE THREAD

**Issue by StefanKiendl** [agnat/node_mdns#104]
I use mdns embedded in AirSonos (via NodeTunes) and always get the following error.

The developer of AirSonos sent me here.

Error message:
---
Error: dns service error: unknown
    at new Advertisement (/usr/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/usr/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/mdns/lib/advertisement.js:64:10)
    at NodeTunes.<anonymous> (/usr/lib/node_modules/airsonos/node_modules/nodetunes/lib/server.js:65:21)
    at Server.g (events.js:180:16)
    at Server.emit (events.js:92:17)
    at net.js:1055:10
    at process._tickCallback (node.js:419:13)

**Comment by beckmx** [comment]
I get the unknown error for OSX, I guess I need avahi or bonjour?


events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: dns service error: unknown
    at Error (native)
    at Advertisement.on_service_registered (/Users/myself/HAP-NodeJS/node_modules/mdns/lib/advertisement.js:42:24)
    at SocketWatcher.MDNSService.self.watcher.callback (/Users/myself/HAP-NodeJS/node_modules/mdns/lib/mdns_service.js:18:40)

**Comment by bobvanderlinden** [comment]
I hope I'm not highjacking this issue with a unrelated one, but the problem seems very similar and has the same exception. Output:
```
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: dns service error: unknown
    at Error (native)
    at MDNSService.on_resolver_done (/home/bob/projects/node-machinetalk-example/node_modules/machinetalk/node_modules/mdns/lib/resolver_sequence_tasks.js:19:30)
    at SocketWatcher.MDNSService.self.watcher.callback (/home/bob/projects/node-machinetalk-example/node_modules/machinetalk/node_modules/mdns/lib/mdns_service.js:18:40)
```
The errorCode (of `on_resolver_done` [here](https://github.com/agnat/node_mdns/blob/master/lib/resolver_sequence_tasks.js#L15)) is `-65537`. I couldn't figure out why this code was sent (any idea?).

This happens while Avahi is running. It seems like it is a timeout from resolving a service on a machine that is non-existant. It might have to do with Avahi having cached a number of services while the machine has been powered off in the meantime. It would explain the semi-randomness I'm seeing.

**Comment by agnat** [comment]
Sorry, no idea. :-/

As a workaround you could obviously trap all unknown errors and (optionally) start a new browser to refresh your lists.

**Comment by bobvanderlinden** [comment]
@agnat Yes, I trap the error, but restarting the browser will again result in an error when it again tries to resolve the incorrect. This even happens when restarting the node process.

That said, reproducing this issue is very flaky (I haven't found a good pattern yet). I'll report back if it happens again.

**Comment by agnat** [comment]
I see. Sounds nasty. Best of luck though!
