### ISSUE TITLE
Tutorial is broken

### ISSUE THREAD

**Issue by appsforartists** [agnat/node_mdns#116]
From [the Tutorial](http://agnat.github.io/node_mdns/user_guide.html#tutorial):

```
var browser = mdns.createBrowser(mdns.tcp('http'));

browser.on('serviceUp', function(service) {
  console.log("service up: ", service);
});
browser.on('serviceDown', function(service) {
  console.log("service down: ", service);
});

browser.start();
```

If I enter the above in a node REPL on Mac OS 10.9.2 running node 0.11.13, I receive this error:

```
> service down:  { interfaceIndex: 4294967295,
  type: 
   { name: 'http',
     protocol: 'tcp',
     subtypes: [],
     fullyQualified: true },
  replyDomain: 'local.',
  flags: 0,
  name: 'Brenton\'s MacBook Pro (eBay)',
  networkInterface: 'lo0' }
Error: dns service error: no such record
    at Error (native)
    at MDNSService.on_get_addr_info_done (/Users/bresimpson/Projects/_misc/node_modules/mdns/lib/resolver_sequence_tasks.js:72:30)
    at SocketWatcher.MDNSService.self.watcher.callback (/Users/bresimpson/Projects/_misc/node_modules/mdns/lib/mdns_service.js:17:38)
> Error: dns service error: no such record
    at Error (native)
    at MDNSService.on_get_addr_info_done (/Users/bresimpson/Projects/_misc/node_modules/mdns/lib/resolver_sequence_tasks.js:72:30)
    at SocketWatcher.MDNSService.self.watcher.callback (/Users/bresimpson/Projects/_misc/node_modules/mdns/lib/mdns_service.js:17:38)
```

**Comment by agnat** [comment]
Without REPL the code works for me on Mac OS 10.9.5 using node v0.11.14 and v0.11.13. Pasting the code in REPL didn't give me the same error but did not work either. It just did nothing. (I never use REPL for stuff like launching servers, so I have no idea if it should work).

I'm not sure how to proceed. Could you run the code from a file? Just to exclude REPL as a source of odd behavior...

**Comment by appsforartists** [comment]
Saved to a file; same error:

```
~/P/_/bonjour $ node --harmony ./index.js 
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: dns service error: no such record
    at Error (native)
    at MDNSService.on_get_addr_info_done (/Users/bresimpson/Projects/_misc/bonjour/node_modules/mdns/lib/resolver_sequence_tasks.js:72:30)
    at SocketWatcher.MDNSService.self.watcher.callback (/Users/bresimpson/Projects/_misc/bonjour/node_modules/mdns/lib/mdns_service.js:17:38)
```

**Comment by agnat** [comment]
Hm. I'm pretty sure it is a local problem. In all these years I've never seen anything like it. Like, _never_.

Actually, it might have something to do with your other issue #117. Let me comment on that one...

**Comment by agnat** [comment]
Thought a bit more about this one. Try installing an error handler on the browser. Maybe it is only _one_ entry that is causing the trouble. Handling the error allows the app to continue processing potential _other_ entries...

**Comment by appsforartists** [comment]
Using this code:
```

var browser = mdns.createBrowser(mdns.tcp('http'));

browser.on('error', function(error) {
  console.error(error.stack);
});
browser.on('serviceUp', function(service) {
  console.log("service up: ", service);
});
browser.on('serviceDown', function(service) {
  console.log("service down: ", service);
});

browser.start();
```

and a `console.log(arguments)` in `on_get_addr_info_done`, I see this:

```
interface index: 0
{ '0': { initialized: true, fd: 19 },
  '1': 3,
  '2': 0,
  '3': -65554,
  '4': 'Brentons-MacBook-Pro-eBay.local.',
  '5': '::',
  '6': 60,
  '7': undefined }
Error: dns service error: no such record
    at Error (native)
    at MDNSService.on_get_addr_info_done (/Users/bresimpson/Projects/_misc/bonjour/node_modules/mdns/lib/resolver_sequence_tasks.js:73:30)
    at SocketWatcher.MDNSService.self.watcher.callback (/Users/bresimpson/Projects/_misc/bonjour/node_modules/mdns/lib/mdns_service.js:17:38)
{ '0': { initialized: true, fd: 20 },
  '1': 3,
  '2': 0,
  '3': -65554,
  '4': 'fonera.local.',
  '5': '::',
  '6': 60,
  '7': undefined }
Error: dns service error: no such record
    at Error (native)
    at MDNSService.on_get_addr_info_done (/Users/bresimpson/Projects/_misc/bonjour/node_modules/mdns/lib/resolver_sequence_tasks.js:73:30)
    at SocketWatcher.MDNSService.self.watcher.callback (/Users/bresimpson/Projects/_misc/bonjour/node_modules/mdns/lib/mdns_service.js:17:38)
{ '0': { initialized: true, fd: 21 },
  '1': 3,
  '2': 0,
  '3': -65554,
  '4': 'HP020983.local.',
  '5': '::',
  '6': 60,
  '7': undefined }
Error: dns service error: no such record
    at Error (native)
    at MDNSService.on_get_addr_info_done (/Users/bresimpson/Projects/_misc/bonjour/node_modules/mdns/lib/resolver_sequence_tasks.js:73:30)
    at SocketWatcher.MDNSService.self.watcher.callback (/Users/bresimpson/Projects/_misc/bonjour/node_modules/mdns/lib/mdns_service.js:17:38)
{ '0': { initialized: true, fd: 22 },
  '1': 3,
  '2': 4,
  '3': 0,
  '4': 'HP9CB654E873F3.local.',
  '5': 'fe80::9eb6:54ff:fee8:73f4',
  '6': 120,
  '7': undefined }
{ '0': { initialized: true, fd: 22 },
  '1': 3,
  '2': 0,
  '3': -65554,
  '4': 'HP9CB654E873F3.local.',
  '5': '::',
  '6': 60,
  '7': undefined }
Error: dns service error: no such record
    at Error (native)
    at MDNSService.on_get_addr_info_done (/Users/bresimpson/Projects/_misc/bonjour/node_modules/mdns/lib/resolver_sequence_tasks.js:73:30)
    at SocketWatcher.MDNSService.self.watcher.callback (/Users/bresimpson/Projects/_misc/bonjour/node_modules/mdns/lib/mdns_service.js:17:38)
service down:  { interfaceIndex: 4294967295,
  type: 
   { name: 'http',
     protocol: 'tcp',
     subtypes: [],
     fullyQualified: true },
  replyDomain: 'local.',
  flags: 0,
  name: 'Brenton\'s MacBook Pro (eBay)',
  networkInterface: 'lo0' }
```

Is that helpful?

**Comment by agnat** [comment]
I still have never seen anything like it and never had a similar bug report.

Closing.
