### ISSUE TITLE
Error when using networkInterface: mdns.loopbackInterface()

### ISSUE THREAD

**Issue by onderweg** [agnat/node_mdns#127]
Hi,

When trying the example for listening to loopback interface

````

var browser = mdns.createBrowser( mdns.tcp('http')
                                , { networkInterface: mdns.loopbackInterface()});
`````

I get the following error:

````
events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: argument 5 must be a string (hostname)
````

**Comment by ssreekanth** [comment]
I'm getting the same error -
```
events.js:154
      throw er; // Unhandled 'error' event
      ^

TypeError: argument 5 must be a string (hostname)
    at TypeError (native)
    at Array.DNSServiceGetAddrInfo (/home/testuser/sample/node_modules/mdns/lib/resolver_sequence_tasks.js:92:14)
    at next (/home/testuser/sample/node_modules/mdns/lib/browser.js:107:21)
    at MDNSService.on_resolver_done (/home/testuser/sample/node_modules/mdns/lib/resolver_sequence_tasks.js:33:11)
    at SocketWatcher.MDNSService.self.watcher.callback (/home/testuser/sample/node_modules/mdns/lib/mdns_service.js:18:40)
```
