### ISSUE TITLE
"Error: getaddrinfo ESRCH" when use mdns on local network without internet access

### ISSUE THREAD

**Issue by tommywang** [agnat/node_mdns#128]
Hi,
When used mdns module on Ubuntu 14.10 on a local network without internet access. The broswer will crash with the following error:
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: getaddrinfo ESRCH
    at errnoException (/home/mina/sources/nodejs/soixante/watchy/node_modules/mdns/lib/resolver_sequence_tasks.js:198:11)
    at getaddrinfo_complete (/home/mina/sources/nodejs/soixante/watchy/node_modules/mdns/lib/resolver_sequence_tasks.js:112:10)
    at Object.wrap.oncomplete (/home/mina/sources/nodejs/soixante/watchy/node_modules/mdns/lib/resolver_sequence_tasks.js:129:7)
```

Our code works fine on a local network with the internet access or on Mac OS without internet.

We create the Advertisement like this:
```
 var mdns = Npm.require('mdns');
  
  ZERO = ZERO || {};

  ZERO.services = [];

  ZERO.initService = function(serviceName, port) {
    ZERO.services.push(mdns.createAdvertisement(mdns.tcp(serviceName), port));
    ZERO.services[ZERO.services.length - 1].start();
  }
``` 

and we try to connect to this service :
```
 var serviceBrowser = mdns.createBrowser(mdns.tcp(serviceName));
      serviceBrowser.on('serviceUp', function(service) {
....
```
So what's the problem? Thanks!

**Comment by agnat** [comment]
The main problem is omission of error handling in real-world code. See [error handling](http://agnat.github.io/node_mdns/user_guide.html#error_handling) for details.

Cheers.

**Comment by tommywang** [comment]
Sure, I already have the part of code in a try-catch error handling. The complete code source is:
```
var handleError = function(error) {
      switch (error.errorCode) {
        case mdns.kDNSServiceErr_Unknown:
          console.warn(error);
          // setTimeout(createAdvertisement, 5000);
          break;
        default:
          // throw error;
          console.log(error);
      }
    };

    try {
      var serviceBrowser = mdns.createBrowser(mdns.tcp(config.servicelookup.name));
      
      serviceBrowser.start();
    } catch (ex) {
      handleError(ex);
    }
```

**Comment by agnat** [comment]
Again, please read the section on error handling. Also take a look at the error message in your initial post. You're going to need an error _event handler_.
