### ISSUE TITLE
Error for _apple-mobdev2 protocol

### ISSUE THREAD

**Issue by jswetzen** [agnat/node_mdns#138]
I'm getting an error on my MacBook (running Yosemite) when browsing for all services:
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: protocol must be either '_tcp' or '_udp' but is '_apple-mobdev2'
    at checkProtocolU (/Users/johan/Projects/websites/node/stagedisplay/node_modules/mdns/lib/service_type.js:184:11)
    at ServiceType.fromString (/Users/johan/Projects/websites/node/stagedisplay/node_modules/mdns/lib/service_type.js:62:3)
    at new ServiceType (/Users/johan/Projects/websites/node/stagedisplay/node_modules/mdns/lib/service_type.js:15:14)
    at Object.makeServiceType (/Users/johan/Projects/websites/node/stagedisplay/node_modules/mdns/lib/service_type.js:133:10)
    at Browser.on_service_changed (/Users/johan/Projects/websites/node/stagedisplay/node_modules/mdns/lib/browser.js:43:19)
    at SocketWatcher.MDNSService.self.watcher.callback (/Users/johan/Projects/websites/node/stagedisplay/node_modules/mdns/lib/mdns_service.js:18:40)
```
It seems like some apple service reports a very strange protocol, but it means that I'm unable to browse all services. Can anyone else reproduce this? This command gives me an error straight away:
```
echo "require('mdns').browseThemAll().start()" | node
```

**Comment by agnat** [comment]
Could be an actual bug. Note that `browseThemAll()` is rather special. It browses for all available _service types_, not services. It might be ok, they don't have a protocol and the parser is just a little to paranoid. I'd apply the remove-offending-line-refactoring around [here](https://github.com/agnat/node_mdns/blob/master/lib/service_type.js#L183-L186) and see what happens.

HTH

**Comment by jswetzen** [comment]
Thank you for the quick reply!

I did not realize that distinction for `browseThemAll()`, and now that I try again I don't get the error, but get this service:
`type: { name: 'apple-mobdev2', protocol: 'tcp', subtypes: [] }`.
Maybe there was some error in parsing so that the name was interpreted as the protocol? It's strange in any case.

The reason I was looking into `browseThemAll()` in the first place was that I wanted to browse for this service type:
```
{ interfaceIndex: 5,
  type: { name: 'pro4_sd', protocol: 'tcp', subtypes: [] },
  replyDomain: '.',
  flags: 3,
  networkInterface: 'en1' }
```
But I get an error for the underline character in the name.
```
service_type.js:163
    throw new Error('type ' + str + ' may only contain alphanumeric ' +
          ^
Error: type pro4_sd may only contain alphanumeric characters and hyphens
    at checkLengthAndCharset (/Users/johan/Projects/websites/node/stagedisplay/node_modules/mdns/lib/service_type.js:163:11)
    at ServiceType.fromArray (/Users/johan/Projects/websites/node/stagedisplay/node_modules/mdns/lib/service_type.js:89:3)
    at new ServiceType (/Users/johan/Projects/websites/node/stagedisplay/node_modules/mdns/lib/service_type.js:24:12)
    at Object.makeServiceType (/Users/johan/Projects/websites/node/stagedisplay/node_modules/mdns/lib/service_type.js:133:10)
    at Object.tcp (/Users/johan/Projects/websites/node/stagedisplay/node_modules/mdns/lib/service_type.js:143:36)
    at Object.<anonymous> (/Users/johan/Projects/websites/node/stagedisplay/bonjour.js:2:39)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```
Is this a bug in mdns or is the service violating the specification by using an underline? I notice that all other services I see use dashes for separation.

**Comment by jswetzen** [comment]
Okay, I saw that the service is actually violating the specification (page 19 of http://www.ietf.org/rfc/rfc6763.txt). I will fork and deviate from the standard because I need to use that service.
