### ISSUE TITLE
Cannot deploy on Heroku

### ISSUE THREAD

**Issue by thanpolas** [agnat/node_mdns#155]
I am no longer able to deploy my app to Heroku due to mdns breaking the build:

```
remote: -----> Exporting config vars to environment
remote: -----> Installing dependencies
remote:        
remote:        > mdns@2.2.11 install /tmp/build_c6e0cfb02c1f8342369e54e17c6a24d8/node_modules/mdns
remote:        > node-gyp rebuild
remote:        
remote:        make: Entering directory `/tmp/build_c6e0cfb02c1f8342369e54e17c6a24d8/node_modules/mdns/build'
remote:          CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
remote:        In file included from ../src/dns_sd.cpp:1:0:
remote:        ../src/mdns.hpp:32:20: fatal error: dns_sd.h: No such file or directory
remote:         #include <dns_sd.h>
remote:                            ^
remote:        compilation terminated.
remote:        make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
remote:        make: Leaving directory `/tmp/build_c6e0cfb02c1f8342369e54e17c6a24d8/node_modules/mdns/build'
remote:        gyp ERR! build error 
remote:        gyp ERR! stack Error: `make` failed with exit code: 2
remote:        gyp ERR! stack     at ChildProcess.onExit (/tmp/build_c6e0cfb02c1f8342369e54e17c6a24d8/vendor/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
remote:        gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
remote:        gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1075:12)
remote:        gyp ERR! System Linux 3.13.0-71-generic
remote:        gyp ERR! command "node" "/tmp/build_c6e0cfb02c1f8342369e54e17c6a24d8/vendor/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
remote:        gyp ERR! cwd /tmp/build_c6e0cfb02c1f8342369e54e17c6a24d8/node_modules/mdns
remote:        gyp ERR! node -v v0.12.9
remote:        gyp ERR! node-gyp -v v3.0.3
remote:        gyp ERR! not ok 
```

Please advise

**Comment by agnat** [comment]
It's in README: You need the `libavahi-compat-libdnssd-dev` package.

**Comment by thanpolas** [comment]
OH! :) sorry!

**Comment by thanpolas** [comment]
Just one question @agnat, our app runs on both osx and linux systems, will installing `libavahi-compat-libdnssd-dev` affect the osx installations and override the use of apple's mDNSResponder?

**Comment by agnat** [comment]
Please read the README. On linux you need the `libavahi-compat-libdnssd-dev`. On OS X you are all set.
