### ISSUE TITLE
node-gyp rebuild fails if --unsafe-perm is not set for sudo npm install -g

### ISSUE THREAD

**Issue by wind-rider** [agnat/node_mdns#164]
I installed homebridge using node 6 on raspberry pi v1.
It is needed to run `sudo npm install -g homebridge --unsafe-perm` (note the last option) or mdns will fail to build.

Sudo is needed to use the -g option but then node-gyp doesn't understand where to build anymore:

`````
node-gyp rebuild
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.0.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/homebridge/node_modules/mdns/.node-gyp"
```````

**Comment by agnat** [comment]
I'm sorry, but nothing in this seems related to mdns. Also, I do not understand why you think this is a bug. To me it seems the `--unsafe-perm` flag is specifically designed to work around such cases.

According to the [documentation](https://docs.npmjs.com/misc/config#unsafe-perm) `--unsafe-perm` defaults to false when running as root (sudo). That means npm will drop privileges before running scripts (node-gyp). node-gyp wants to download stuff into `$HOME/.node-gyp/` which fails because it does not have permissions to do that...

**Comment by troyanskiy** [comment]
@wind-rider did you solve installation problem? I have the same with homebridge on synology

```
sudo npm i -g mdns
node: /lib/libstdc++.so.6: no version information available (required by node)
node: /lib/libstdc++.so.6: no version information available (required by node)

> mdns@2.3.3 install /volume1/homes/admin/node-v6.2.2-linux-x86/lib/node_modules/mdns
> node-gyp rebuild

node: /lib/libstdc++.so.6: no version information available (required by node)
node: /lib/libstdc++.so.6: no version information available (required by node)
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.2.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/volume1/homes/admin/node-v6.2.2-linux-x86/lib/node_modules/mdns/.node-gyp"
node: /lib/libstdc++.so.6: no version information available (required by node)
node: /lib/libstdc++.so.6: no version information available (required by node)
gyp: Call to 'node -e "require('nan')"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/volume1/homes/admin/node-v6.2.2-linux-x86/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.2.40
gyp ERR! command "/volume1/homes/admin/node-v6.2.2-linux-x86/bin/node" "/volume1/homes/admin/node-v6.2.2-linux-x86/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /volume1/homes/admin/node-v6.2.2-linux-x86/lib/node_modules/mdns
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Linux 3.2.40
npm ERR! argv "/volume1/homes/admin/node-v6.2.2-linux-x86/bin/node" "/usr/local/bin/npm" "i" "-g" "mdns"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE

npm ERR! mdns@2.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.3.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mdns
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /volume1/homes/admin/node-v6.2.2-linux-x86/bin/npm-debug.log
```

**Comment by wind-rider** [comment]
@troyanskiy that depends on what you call "solved" -> I used --unsafe-perm and after that I haven't tried it anymore
