### ISSUE TITLE
node_mdns Examples not running on QNX

### ISSUE THREAD

**Issue by rameshpasunoori** [agnat/node_mdns#169]
Hi All

I am new to node.js and mdns.
I ported the node.js to QNX and tested some sample applications.

I downloaded the node_mdns package and copied to QNX.
Tried to execute the example application.
Facing issue related **"dns_sd_bindings"**

# node examples/osc_devices.js                                        
premain 123 
In Main() 123 
module.js:327
    throw err;
    ^

**Error: Cannot find module '../build/Release/dns_sd_bindings'**
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/datastore/node-v4.4.3/armle-v7/lib/node_modules/mdns/lib/dns_sd.js:32:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

I tried to generate dns_sd_bindings using node-gyp, but facing issues.

Please give some input on this.

Regards
Ramesh

**Comment by agnat** [comment]
> I tried to generate dns_sd_bindings using node-gyp, but facing issues.

node_mdns requires either the apple bonjour stack (recommended) or avahi and its compat library (see the README). So, the next step is probably to compile the apple bonjour code for QNX...

**Comment by ingsaurabh** [comment]
Does this means apple bonjour stack/avahi to be installed on user machine for release also

**Comment by agnat** [comment]
Yes. You need _either_ avahi and the compat library _or_ apples mDNSResponder. mDNSResponder works considerably better than the compat library.
