### ISSUE TITLE
can not create a node package for MIPS openwrt

### ISSUE THREAD

**Issue by cnliri1** [agnat/node_mdns#185]
The mdns node_modules can not run on wndr4300 with openwrt. If this caused by cross compile failure or somthing else?Can someone help about it?

Error log as below

node: '/root/HAP-NodeJS/node_modules/mdns/build/Release/dns_sd_bindings.node' is not an ELF executable for MIPS

/root/HAP-NodeJS/node_modules/mdns/lib/dns_sd.js:35
    throw ex;
          ^
Error: File not found
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/HAP-NodeJS/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by js-john** [comment]
did you get solution? I met the same problem as your case

**Comment by cnliri1** [comment]
@js-john nothing update..

**Comment by agnat** [comment]
> [...] dns_sd_bindings.node is not an ELF executable for MIPS

Yes, that is a cross-compilation issue. :)

AFAIK, cross-compiling node add-ons is not really supported. You will have to write your own makefile.
