### ISSUE TITLE
node-gyp rebuild error on Ubuntu 16.04 via npm

### ISSUE THREAD

**Issue by toe-kne3** [agnat/node_mdns#187]
Tried to install mdns through npm. Already installed `libavahi-compat-libdnssd-dev` through apt but when i run `sudo npm install -g mdns` I keep getting:

>user@server:~$ sudo npm install -g mdns
>
>> mdns@2.3.3 install /usr/local/lib/node_modules/mdns
>> node-gyp rebuild
>
>/usr/bin/env: 'node': No such file or directory
>npm ERR! Linux 4.4.0-66-generic
>npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "mdns"
>npm ERR! node v4.2.6
>npm ERR! npm  v3.5.2
>npm ERR! file sh
>npm ERR! code ELIFECYCLE
>npm ERR! errno ENOENT
>npm ERR! syscall spawn
>
>npm ERR! mdns@2.3.3 install: `node-gyp rebuild`
>npm ERR! spawn ENOENT
>npm ERR!
>npm ERR! Failed at the mdns@2.3.3 install script 'node-gyp rebuild'.
>npm ERR! Make sure you have the latest version of node.js and npm installed.
>npm ERR! If you do, this is most likely a problem with the mdns package,
>npm ERR! not with npm itself.
>npm ERR! Tell the author that this fails on your system:
>npm ERR!     node-gyp rebuild
>npm ERR! You can get information on how to open an issue for this project with:
>npm ERR!     npm bugs mdns
>npm ERR! Or if that isn't available, you can get their info via:
>npm ERR!     npm owner ls mdns
>npm ERR! There is likely additional logging output above.

**Comment by agnat** [comment]
Hi @toe-kne3 

> /usr/bin/env: 'node': No such file or directory

Seems like `node` is not installed... or not in the path when running `sudo`. Make sure `sudo node -v` works.

HTH

**Comment by toe-kne3** [comment]
Thanks for the quick reply.
Seems like you are right. When i run `sudo node -v`, node isnt not found. but if i run without `sudo`, I'm asked to install `node-legacy`. So should i install it or is there a newer/up-to-date version that is the apt-cache like, from a quick search, `node-cli`?

**Comment by agnat** [comment]
Sorry, but I don't know. Installing the version that ships with the distro (`node-legacy`) sounds like the sensible thing. Maybe just google what others are using?

**Comment by toe-kne3** [comment]
Did some research and found that installing from the official ppa, following the instructions here: [https://tecadmin.net/install-latest-nodejs-npm-on-ubuntu/](url) and it installed node. If i run `node -v` it returns `vX.X.X` But when I tried to install mdns again, I get this error

>toe-kne3@Prometheus:~$ sudo npm install -g mdns
>
>> mdns@2.3.3 install /usr/local/lib/node_modules/mdns
>> node-gyp rebuild
>
>gyp ERR! UNCAUGHT EXCEPTION
>gyp ERR! stack Error: spawn EACCES
>gyp ERR! stack     at exports._errnoException (util.js:870:11)
>gyp ERR! stack     at ChildProcess.spawn (internal/child_process.js:298:11)
>gyp ERR! stack     at exports.spawn (child_process.js:362:9)
>gyp ERR! stack     at Object.exports.execFile (child_process.js:151:15)
>gyp ERR! stack     at Object.checkPythonVersion (/usr/local/lib/node_modules/node-gyp/lib/configure.js:417:10
>gyp ERR! stack     at Object.<anonymous> (/usr/local/lib/node_modules/node-gyp/lib/configure.js:376:14)
>gyp ERR! stack     at /usr/local/lib/node_modules/node-gyp/node_modules/which/which.js:87:20
>gyp ERR! stack     at /usr/local/lib/node_modules/node-gyp/node_modules/isexe/index.js:44:5
>gyp ERR! stack     at /usr/local/lib/node_modules/node-gyp/node_modules/isexe/access.js:8:5
>gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
>gyp ERR! System Linux 4.4.0-66-generic
>gyp ERR! command "/usr/bin/nodejs" "/usr/local/bin/node-gyp" "rebuild"
>gyp ERR! cwd /usr/local/lib/node_modules/mdns
>gyp ERR! node -v v4.2.6
>gyp ERR! node-gyp -v v3.5.0
>gyp ERR! This is a bug in `node-gyp`.
>gyp ERR! Try to update node-gyp and file an Issue if it does not help:
>gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
>npm ERR! Linux 4.4.0-66-generic
>npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "mdns"
>npm ERR! node v4.2.6
>npm ERR! npm  v3.5.2
>npm ERR! code ELIFECYCLE
>
>npm ERR! mdns@2.3.3 install: `node-gyp rebuild`
>npm ERR! Exit status 7
>npm ERR!
>npm ERR! Failed at the mdns@2.3.3 install script 'node-gyp rebuild'.
>npm ERR! Make sure you have the latest version of node.js and npm installed.
>npm ERR! If you do, this is most likely a problem with the mdns package,
>npm ERR! not with npm itself.
>npm ERR! Tell the author that this fails on your system:
>npm ERR!     node-gyp rebuild
>npm ERR! You can get information on how to open an issue for this project with:
>npm ERR!     npm bugs mdns
>npm ERR! Or if that isn't available, you can get their info via:
>npm ERR!     npm owner ls mdns
>npm ERR! There is likely additional logging output above.

**Comment by agnat** [comment]
From looking at the stack it seems it can't find or access python:

> gyp ERR! stack at Object.checkPythonVersion (/usr/local/lib/node_modules/node-gyp/lib/configure.js:417:10

... which is required by node-gyp.

**Comment by toe-kne3** [comment]
Here's the log file for further information [http://pastebin.com/BddhjffW](pastebin)
