### ISSUE TITLE
Procedure not found error when trying to run as part of airsonos

### ISSUE THREAD

**Issue by Tiger519** [agnat/node_mdns#188]
I'm on Windows 10, running node.js 5.0.0 (I believe I need this version for HomeBridge), and I'm experiencing an error when trying to run airsonos. mdns is installed via nodetunes. It's saying the specified procedure is not found within the module. Here is the full text of the error. Any ideas?

C:\Users\coolt\AppData\Roaming\npm>airsonos
C:\Users\coolt\AppData\Roaming\npm\node_modules\airsonos\node_modules\nodetunes\node_modules\mdns\lib\dns_sd.js:35
    throw ex;
    ^

Error: The specified procedure could not be found.
\\?\C:\Users\coolt\AppData\Roaming\npm\node_modules\airsonos\node_modules\nodetunes\node_modules\mdns\build\Release\dns_sd_bindings.node
    at Error (native)
    at Object.Module._extensions..node (module.js:450:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\coolt\AppData\Roaming\npm\node_modules\airsonos\node_modules\nodetunes\node_modules\mdns\lib\dns_sd.js:24:20)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)

**Comment by RichardFoss** [comment]
I have been trying to resolve the same issue on Windows. 
My code works fine on a Mac. mdns builds with nw-gyp.
I did a: nw-gyp rebuild --target=0.33.4 --arch=x64
I'm using node v12.12.0 and npm v6.11.3

On doing:
 var mdns = require('mdns');
I get the message below. Help would be much appreciated!
--------------------------------------
Uncaught Error: The specified procedure could not be found.
\\?\D:\Git-Repos\ImmerGo-MOTU\immergo-motu\node_modules\mdns\build\Release\dns_sd_bindings.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1048:18)
    at Module.load (internal/modules/cjs/loader.js:836:32)
    at Function.Module._load (internal/modules/cjs/loader.js:748:14)
    at Module.require (internal/modules/cjs/loader.js:873:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\Git-Repos\ImmerGo-MOTU\immergo-motu\node_modules\mdns\lib\dns_sd.js:24:20)
    at Module._compile (internal/modules/cjs/loader.js:980:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1003:10)
    at Module.load (internal/modules/cjs/loader.js:836:32)
    at Function.Module._load (internal/modules/cjs/loader.js:748:14)
