### ISSUE TITLE
Unhandled 'error' event on npm test

### ISSUE THREAD

**Issue by lollotek** [agnat/node_mdns#198]
I got problems on running the sample code, so I tryed the test as on readme:
> If you want to play with the latest source code, here is a more manual approach:
> git clone http://github.com/agnat/node_mdns
> cd node_mdns
> npm link && npm test

And This is the error message:

```
mdns@2.3.3 test /media/lorenzo/Data/_progetti/nerd-caverna/wordclock2/test-mdns/node_mdns
node utils/testrun

*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>

test_browser

Browser
✔ Should retrieve interface name from cache when interface index is no longer valid  [4/4]
✔ Should survive invalid MDNS advert                                                 [1/1]

test_dns_sd
✔ DNSServiceRef                 [3/3]
✔ DNSServiceRegister()          [20/20]
✔ DNSServiceProcessResult()     [13/13]
✔ DNSServiceRefSockFD()         [6/6]
✔ DNSServiceBrowse()            [13/13]
✔ DNSServiceRefDeallocate()     [8/8]
✔ DNSServiceResolve()           [11/11]
*** WARNING *** The program 'node' called 'DNSServiceEnumerateDomains()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceEnumerateDomains>
✔ DNSServiceEnumerateDomains()  [13/13]
[SKIPPED] DNSServiceGetAddrInfo() not available
✔ DNSServiceGetAddrInfo         [0/0]
[SKIPPED] avahi doesn't support null values
[SKIPPED] avahi doesn't support undefined values
✔ TXTRecordRef                  [29/29]
✔ buildException()              [47/47]
✔ exportConstants()             [3/3]

test_functional
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo -3008
    at errnoException (/media/lorenzo/Data/node_mdns/lib/resolver_sequence_tasks.js:199:11)
    at getaddrinfo_complete (/media/lorenzo/Data/node_mdns/lib/resolver_sequence_tasks.js:112:10)
    at GetAddrInfoReqWrap.oncomplete (/media/lorenzo/Data/node_mdns/lib/resolver_sequence_tasks.js:120:9)
```
I have already installed libavahi-compat-libdnssd-dev
ping device from my pc also works

System info: 
Ubuntu 17.04 64-bit
npm: 5.4.0
node: 8.4.0

Thanks

**Comment by lollotek** [comment]
I'm not secure if is related, I also tryed to stop avahi-daemon, but nothing changed.

I also fount this in examples:
> //if you have avahi or bonjour or other mdns service running on the same system
> //you REALLY would like to exlude 0.0.0.0 from the interfaces bound to
> //mdns.excludeInterface('0.0.0.0')

But also in this case, decommenting I got trubles:
```
mdns.excludeInterface('0.0.0.0')
     ^

TypeError: mdns.excludeInterface is not a function
    at Object.<anonymous> (/media/lorenzo/Data/_proge
```
