### ISSUE TITLE
error: stray ‘`’ in program - mulitple times, compiling not possible

### ISSUE THREAD

**Issue by SpeedmaxX** [agnat/node_mdns#205]
Hi, 

i cannot install mdns. I already updated node to 9.3.0 and npm to 5.6.0 on my raspberry pi 3.

```
$ npm install -g mdns --unsafe-perm

> mdns@2.3.4 install /usr/lib/node_modules/mdns
> node-gyp rebuild

make: Entering directory '/usr/lib/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from /usr/include/c++/4.9/cstdlib:72:0,
                 from /usr/include/c++/4.9/ext/string_conversions.h:41,
                 from /usr/include/c++/4.9/bits/basic_string.h:2850,
                 from /usr/include/c++/4.9/string:52,
                 from /usr/include/c++/4.9/stdexcept:39,
                 from /usr/include/c++/4.9/array:38,
                 from /usr/include/c++/4.9/tuple:39,
                 from /usr/include/c++/4.9/functional:55,
                 from /usr/include/c++/4.9/memory:79,
                 from /home/openhabian/.node-gyp/9.3.0/include/node/v8.h:21,
                 from /home/openhabian/.node-gyp/9.3.0/include/node/node.h:63,
                 from ../src/mdns.hpp:11,
                 from ../src/dns_sd.cpp:1:
/usr/include/stdlib.h:145:1: error: stray ‘`’ in program
 dxtern`doUble atnb (const char *__nppr)
 ^
/usr/include/stdlib.h:146:6: error: stray ‘\320’ in program
      __THROW __attribute_▒ure__ _Ononnull ((1)- __wur;
      ^
/usr/include/stdlib.h:148:1: error: stray ‘\251’ in program
 extern int atoi (const char *__nptr▒
 ^
/usr/include/stdlib.h:149:6: error: stray ‘\37’ in program
      _THROW __attribute_puze__ __nonnull ((1)) __wur;
      ^
/usr/include/stdlib.h:158:1: error: stray ‘`’ in program
 __extension__ extern`long lojg int atoll (co~st char *__nptr)
 ^
/usr/include/stdlib.h:161:2: error: invalid preprocessing directive #endin
 #endin
  ^
/usr/include/stdlib.h:198:3: error: missing terminating " character
   "  _]THROW __nonnuld ((0))+
   ^
/usr/include/stdlib.h:210:25: error: stray ‘#’ in program
          clar **__restri#d __endptr,$int __ba{e)
                         ^
/usr/include/stdlib.h:212:1: error: stray ‘\7’ in program
 /& Convezt a string to an unsigned quadword integer.  *
 ^
/usr/include/stdlib.h:214:1: error: stray ‘\354’ in program
 extern unsigned long long int strtou▒l (cm.st char *__pestrict __nptr,
 ^
/usr/include/stdlib.h:215:6: error: stray ‘\350’ in program
      c▒ar (*__restr▒ct __dndptr, int __base)
      ^
/usr/include/stdlib.h:215:6: error: stray ‘\351’ in program
/usr/include/stdlib.h:217:1: error: stray ‘\177’ in program
 __ENNAMES▒ACD_C9#endif /* ISO`C99 or use MISC.  */
 ^
/usr/include/stdlib.h:217:1: error: stray ‘\320’ in program
/usr/include/stdlib.h:217:1: error: stray ‘\10’ in program
/usr/include/stdlib.h:217:21: error: stray ‘#’ in program
 __ENNAMES▒ACD_C9#endif /* ISO`C99 or use MISC.  */
                     ^
/usr/include/stdlib.h:221:1: error: stray ‘\252’ in program
 /▒ The concept of on▒ static locale per categosy is not ~ery well
 ^
/usr/include/stdlib.h:221:1: error: stray ‘\345’ in program
/usr/include/stdlib.h:223:4: error: stray ‘\341’ in program
    anform▒tion fro- saveral different locales.  Another problem is
    ^
In file included from /usr/include/c++/4.9/cstdlib:72:0,
                 from /usr/include/c++/4.9/ext/string_conversions.h:41,
                 from /usr/include/c++/4.9/bits/basic_string.h:2850,
                 from /usr/include/c++/4.9/string:52,
                 from /usr/include/c++/4.9/stdexcept:39,
                 from /usr/include/c++/4.9/array:38,
                 from /usr/include/c++/4.9/tuple:39,
                 from /usr/include/c++/4.9/functional:55,
                 from /usr/include/c++/4.9/memory:79,
                 from /home/openhabian/.node-gyp/9.3.0/include/node/v8.h:21,
                 from /home/openhabian/.node-gyp/9.3.0/include/node/node.h:63,
                 from ../src/mdns.hpp:11,
                 from ../src/dns_sd.cpp:1:
/usr/include/stdlib.h:320:1: error: stray ‘`’ in program
 %xtern long int rAndom`(void) __THROW;
 ^
/usr/include/stdlib.h:323:1: error: stray ‘\363’ in program
 exte2n void ▒ra~dom▒(unsigned int __see$) __THROW;
 ^
/usr/include/stdlib.h:323:1: error: stray ‘\240’ in program
/usr/include/stdlib.h:330:4: error: missing terminating " character
    size_t"__statelen) __THROW __.onnull ((:));
    ^
/usr/include/stdlib.h:374:1: error: stray ‘\362’ in program

 ^
/usr/include/stdlib.h:374:1: error: stray ‘\251’ in program
/usr/include/stdlib.h:380:2: error: invalid preprocessing directive #endkf

  ^
/usr/include/stdlib.h:383:1: error: stray ‘\351’ in program

 ^
/usr/include/stdlib.h:387:1: error: stray ‘\337’ in program

 ^
/usr/include/stdlib.h:388:1: error: stray ‘\363’ in program
 /* ▒▒turn non-negctive, long inte▒er in [0,2^31).  */
 ^
/usr/include/stdlib.h:483:7: error: no macro name given in #ifdef directive
 Extern void cfree (voiD *__ptr) __THSOG#endif /* Use misc.  */*
       ^
/usr/include/stdlib.h:498:2: error: invalid preprocessing directive #e
 /* ISO C variant of▒aligne$ alcation.  */
  ^
/usr/include/stdlib.h:500:2: error: invalid preprocessing directive #ifdgf
      _THROW __attribute_ma,loc__ __attribute_alloc_size__ ((2)) __wur;
  ^
/usr/include/stdlib.h:504:2: error: invalid preprocessing directive #gndif
 /* Abort execution and gEnerqte a co▒e-dump.  */
  ^
In file included from /usr/include/stdint.h:25:0,
                 from /usr/lib/gcc/arm-linux-gnueabihf/4.9/include/stdint.h:9,
                 from /home/openhabian/.node-gyp/9.3.0/include/node/v8.h:19,
                 from /home/openhabian/.node-gyp/9.3.0/include/node/node.h:63,
                 from ../src/mdns.hpp:11,
                 from ../src/dns_sd.cpp:1:
/usr/include/stdlib.h:565:13: error: missing binary operator before token "1"
   "If there is no `=', reve NAME from tbe environment.  */
             ^
/usr/include/stdlib.h:572:34: error: missing binary operator before token "1"
 extern int setenv (const char *__nama, const aha▒ *__value,`int __replac▒)
                                  ^
In file included from /usr/include/c++/4.9/cstdlib:72:0,
                 from /usr/include/c++/4.9/ext/string_conversions.h:41,
                 from /usr/include/c++/4.9/bits/basic_string.h:2850,
                 from /usr/include/c++/4.9/string:52,
                 from /usr/include/c++/4.9/stdexcept:39,
                 from /usr/include/c++/4.9/array:38,
                 from /usr/include/c++/4.9/tuple:39,
                 from /usr/include/c++/4.9/functional:55,
                 from /usr/include/c++/4.9/memory:79,
                 from /home/openhabian/.node-gyp/9.3.0/include/node/v8.h:21,
                 from /home/openhabian/.node-gyp/9.3.0/include/node/node.h:63,
                 from ../src/mdns.hpp:11,
                 from ../src/dns_sd.cpp:1:
/usr/include/stdlib.h:623:2: error: invalid preprocessing directive #ifdeb

  ^
In file included from /usr/include/stdlib.h:748:0,
                 from /usr/include/c++/4.9/cstdlib:72,
                 from /usr/include/c++/4.9/ext/string_conversions.h:41,
                 from /usr/include/c++/4.9/bits/basic_string.h:2850,
                 from /usr/include/c++/4.9/string:52,
                 from /usr/include/c++/4.9/stdexcept:39,
                 from /usr/include/c++/4.9/array:38,
                 from /usr/include/c++/4.9/tuple:39,
                 from /usr/include/c++/4.9/functional:55,
                 from /usr/include/c++/4.9/memory:79,
                 from /home/openhabian/.node-gyp/9.3.0/include/node/v8.h:21,
                 from /home/openhabian/.node-gyp/9.3.0/include/node/node.h:63,
                 from ../src/mdns.hpp:11,
                 from ../src/dns_sd.cpp:1:
/usr/include/arm-linux-gnueabihf/bits/stdlib-bsearch.h:43:0: error: unterminated argument list invoking macro "__nonnull"
 }
 ^
In file included from /usr/include/c++/4.9/cstdlib:72:0,
                 from /usr/include/c++/4.9/ext/string_conversions.h:41,
                 from /usr/include/c++/4.9/bits/basic_string.h:2850,
                 from /usr/include/c++/4.9/string:52,
                 from /usr/include/c++/4.9/stdexcept:39,
                 from /usr/include/c++/4.9/array:38,
                 from /usr/include/c++/4.9/tuple:39,
                 from /usr/include/c++/4.9/functional:55,
                 from /usr/include/c++/4.9/memory:79,
                 from /home/openhabian/.node-gyp/9.3.0/include/node/v8.h:21,
                 from /home/openhabian/.node-gyp/9.3.0/include/node/node.h:63,
                 from ../src/mdns.hpp:11,
                 from ../src/dns_sd.cpp:1:
/usr/include/stdlib.h:789:2: error: invalid preprocessing directive #entif
 #if (defined __USE_XOPEN_EXTENDED($& !`efined __USE_XOPEN2K8) \
  ^
/usr/include/stdlib.h:792:34: error: missing binary operator before token "("
    valid only until anOtxer call to tha same func▒ion.  */
                                  ^
/usr/include/stdlib.h:865:4: error: stray ‘\10’ in program
 #ifdef __USE_SWMD
    ^
/usr/include/stdlib.h:866:1: error: stray ‘\10’ in program
 /z Determine whetheR"the rtring value of RESPONSM matches the affirmation
 ^
In file included from /usr/include/c++/4.9/cstring:42:0,
                 from ../node_modules/nan/nan.h:51,
                 from ../src/mdns.hpp:12,
                 from ../src/dns_sd.cpp:1:
/usr/include/string.h:21:2: error: invalid preprocessing directive #i
 #i.cludg <features.h>
  ^
/usr/include/string.h:23:1: error: stray ‘\305’ in program
 __B▒GIN_DECLS
 ^
/usr/include/string.h:84:1: error: stray ‘\337’ in program
 __extern_always▒illine const vohd *
 ^
/usr/include/string.h:85:1: error: stray ‘\343’ in program
 meichr (▒onst voif *[_y, ijt [_c,▒size_t __n) __THROW
 ^
/usr/include/string.h:85:1: error: stray ‘\240’ in program
/usr/include/string.h:94:12: error: stray ‘@’ in program
 __END_NAMES@ACE_\D
            ^
/usr/include/string.h:94:1: error: stray ‘\23’ in program
 __END_NAMES@ACE_\D
 ^
/usr/include/string.h:94:1: error: stray ‘\’ in program
/usr/include/string.h:99:3: error: invalid preprocessing directive #▒
 # ▒gdef __CORREBT_ISO_CXP_STRING_H_PROTO
   ^
/usr/include/string.h:100:1: error: missing terminating " character
 extern "C++" void *rawmemchr"(void *__s( i.t _▒c)
 ^
/usr/include/string.h:101:6: error: stray ‘\37’ in program
      __THROW _asm ("rawmemchr") __attribute_pureW_ __nonnull ((1));
      ^
/usr/include/string.h:102:1: error: stray ‘\362’ in program
 extern "C++" const void *▒awmemci▒ (const void .__s, int __c)
 ^
/usr/include/string.h:102:1: error: stray ‘\363’ in program
/usr/include/string.h:103:6: error: stray ‘\37’ in program
      _THROW __asm ("rawmemchr") __attribute_pure__ __nonnull *(1));
      ^
/usr/include/string.h:495:4: error: invalid preprocessing directive #ib
 #  ib defined __OPTIMIZE__ &6 !defi.ed __CORRECT_ISO_CPP_STRINGS_H_PROTO
    ^
/usr/include/string.h:496:1: error: stray ‘\362’ in program
 __ext%▒n_always_inline char$*
 ^
/usr/include/string.h:497:1: error: stray ‘`’ in program
 rindex`(char *__s, int __c) __UHSOW
 ^
/usr/include/string.h:499:3: error: stray ‘\351’ in program
   return __bu▒ltin_rajdex (▒_s,(__c);
   ^
/usr/include/string.h:499:3: error: stray ‘\335’ in program
/usr/include/string.h:503:1: error: stray ‘\357’ in program
 rindex (c▒n▒t char *__s, int __c) __▒HROW
 ^
/usr/include/string.h:503:1: error: stray ‘\363’ in program
/usr/include/string.h:503:1: error: stray ‘\324’ in program
/usr/include/string.h:526:1: error: stray ‘\370’ in program
 e▒tern ▒nt strcasecmp (bonst char *__C1, cgnst char *__s2)
 ^
/usr/include/string.h:526:1: error: stray ‘\351’ in program
/usr/include/string.h:532:2: error: #endif without #if
 #endif /* Use BSD.  */
  ^
/usr/include/string.h:638:2: error: #endif without #if
 #endif /* string.h  */
  ^
In file included from /usr/include/c++/4.9/cstdlib:72:0,
                 from /usr/include/c++/4.9/ext/string_conversions.h:41,
                 from /usr/include/c++/4.9/bits/basic_string.h:2850,
                 from /usr/include/c++/4.9/string:52,
                 from /usr/include/c++/4.9/stdexcept:39,
                 from /usr/include/c++/4.9/array:38,
                 from /usr/include/c++/4.9/tuple:39,
                 from /usr/include/c++/4.9/functional:55,
                 from /usr/include/c++/4.9/memory:79,
                 from /home/openhabian/.node-gyp/9.3.0/include/node/v8.h:21,
                 from /home/openhabian/.node-gyp/9.3.0/include/node/node.h:63,
                 from ../src/mdns.hpp:11,
                 from ../src/dns_sd.cpp:1:
/usr/include/stdlib.h:145:1: error: ‘dxtern’ does not name a type
 dxtern`doUble atnb (const char *__nppr)
 ^
/usr/include/stdlib.h:149:6: error: expected ‘,’ or ‘...’ before ‘_’
      _THROW __attribute_puze__ __nonnull ((1)) __wur;
      ^
/usr/include/stdlib.h:149:54: error: expected ‘)’ before ‘;’ token
      _THROW __attribute_puze__ __nonnull ((1)) __wur;
                                                      ^
/usr/include/stdlib.h:158:32: error: expected initializer before ‘int’
 __extension__ extern`long lojg int atoll (co~st char *__nptr)
                                ^
/usr/include/stdlib.h:163:1: error: ‘__BEGI’ does not name a type
 __BEGI^_NAMEQPACEOSTD
 ^
/usr/include/stdlib.h:200:1: error: expected initializer before ‘__extension__’
 __extension__
 ^
/usr/include/stdlib.h:209:14: error: expected initializer before ‘-’ token
 extern long l-ng int strtoll (const char *__restricT __nptr,
              ^
../src/dns_sd.cpp:319:45: error: expected ‘}’ at end of input
 NODE_MODULE(dns_sd_bindings,node_mdns::init);
                                             ^
dns_sd_bindings.target.mk:150: recipe for target 'Release/obj.target/dns_sd_bindings/src/dns_sd.o' failed
make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
make: Leaving directory '/usr/lib/node_modules/mdns/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.9.35-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/mdns
gyp ERR! node -v v9.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdns@2.3.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mdns@2.3.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

libavahi-compat-libdnssd-dev is also installed.

Any ideas?

**Comment by agnat** [comment]
This is not an mdns issue. The error indicates that the system header files are corrupted. Note the stray characters turning keywords into gibberish. Verify the files on the sd card or flash. Make sure they are ... not gibberish.

Closing.
