### ISSUE TITLE
Can't install mdns on ubuntu 14

### ISSUE THREAD

**Issue by WebberLai** [agnat/node_mdns#208]
I try to install mdns , I use 

`npm install mdns`

and wait few seconds ...

it shows 

```
> mdns@2.3.4 install /etc/hardware/node_modules/mdns
> node-gyp rebuild

/usr/lib/node_modules/make/bin/make.js:7
const { existsSync: exists } = fs;
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Linux 3.12.10+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /etc/hardware/node_modules/mdns
gyp ERR! node -v v4.8.7
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Linux 3.12.10+
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "mdns"
npm ERR! node v4.8.7
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! mdns@2.3.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.3.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mdns
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /etc/hardware/npm-debug.log

```

Did I miss anything I need to install first ???

**Comment by agnat** [comment]
This is not an mdns issue. Apparently, there is an npm package called `make` with an executable of the same name. It seems to be installed globally and it is broken:

````
/usr/lib/node_modules/make/bin/make.js:7
const { existsSync: exists } = fs;
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
````

Remove the broken package, install GNU make proper and see the install section of the README for additional dependencies. 

Closing.
