### ISSUE TITLE
Can anyone tell why i m facing this error?

### ISSUE THREAD

**Issue by vinothmoorthkumar** [agnat/node_mdns#209]
Error: /root/project/node_modules/mdns/build/Release/dns_sd_bindings.node: wrong ELF class: ELFCLASS64
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/project/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/project/node_modules/mdns/lib/mdns.js:1:77)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by ronkorving** [comment]
Looks like you've built it on a 64 bit OS, and are trying to run it on a 32 bit OS?
