### ISSUE TITLE
Error trying to install mdns in npm

### ISSUE THREAD

**Issue by StevensCol** [agnat/node_mdns#219]
Hi! I've trying to install the mdns module but i get the next error in npm:

OS:

```
Fedora 28

$ uname -r
4.17.7-200.fc28.x86_64
```

Node version:
```
$ node -v
v8.11.3
```
npm version:

```
$ npm -v
6.1.0
```

And the error is:

```
$ npm i -S mdns

> mdns@2.4.0 install /home/poli/Develop/media-chromecast-server/node_modules/mdns
> node-gyp rebuild

make: se entra en el directorio '/home/poli/Develop/media-chromecast-server/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:
../src/mdns.hpp:32:10: error fatal: dns_sd.h: No such file or directory
 #include <dns_sd.h>
          ^~~~~~~~~~
compilación terminada.
make: *** [dns_sd_bindings.target.mk:153: Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
make: se sale del directorio '/home/poli/Develop/media-chromecast-server/node_modules/mdns/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.17.7-200.fc28.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/poli/Develop/media-chromecast-server/node_modules/mdns
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN media-chromecast-server@0.0.1 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdns@2.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/poli/.npm/_logs/2018-07-27T20_31_19_470Z-debug.log
```

Thanks!

**Comment by agnat** [comment]
Follow the installation section of the README.
