### ISSUE TITLE
node_mdns run in docker failed

### ISSUE THREAD

**Issue by gedennis** [agnat/node_mdns#227]
When I docker build my project with node_mdns, It met error. And when I docker run it.It failed.
Dockerfile:
```
FROM node:8 
LABEL maintainer dennis.ge<gedennis@163.com>

WORKDIR /usr/src/app

ARG NODE_ENV
ENV NODE_ENV $NODE_ENV
COPY package.json /usr/src/app/

RUN apt-get update && \
    apt-get install libavahi-compat-libdnssd-dev  -y
RUN npm install

COPY device /usr/src/app/device
COPY utils /usr/src/app/utils
RUN ls

CMD [ "node", "/usr/src/app/device/index.js" ]
```
error stack:
```
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2019-03-18T15:50:27.149] [INFO] DEVICE - Device PRM#PHONE is on, components initing ...
[2019-03-18T15:50:27.154] [INFO] DEVICE - mDNS browser init start ...
/usr/src/app/node_modules/mdns/lib/browser.js:86
  dns_sd.DNSServiceBrowse(self.serviceRef, flags, ifaceIdx, '' + requested_type,
         ^

Error: dns service error: unknown
    at new Browser (/usr/src/app/node_modules/mdns/lib/browser.js:86:10)
    at Object.create [as createBrowser] (/usr/src/app/node_modules/mdns/lib/browser.js:114:10)
    at Device.createBrowser (/usr/src/app/device/device.js:29:26)
    at Device.init (/usr/src/app/device/device.js:92:10)
    at Object.<anonymous> (/usr/src/app/device/index.js:20:8)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```
Thx for ur help

**Comment by agnat** [comment]
I don't have much experience using docker, but...

1. If it does not build it will not run...
2. Make sure your docker image starts the avahi service... just installing the header files is not enough

**Comment by gedennis** [comment]
@agnat Thx for ur answer. Do u mean, libavahi-compat-libdnssd-dev I installed is just the header files. I need to start the avahi service on my ubuntu server, is that right?

**Comment by agnat** [comment]
> Do u mean, libavahi-compat-libdnssd-dev I installed is just the header files.

Yes. It probably installs a few additional dependencies but the `-dev` package is just header files.

> I need to start the avahi service on my ubuntu server, is that right?

No. You need to install and run the avahi service in your docker image.

**Comment by aessig** [comment]
@molinjun did you find a way to make it work?
