### ISSUE TITLE
Error on node-gyp

### ISSUE THREAD

**Issue by 3l0w** [agnat/node_mdns#239]
I try to install mdns but i got a error:

`
H:\dev\chromecast>npm i mdns

> mdns@2.5.1 install H:\dev\chromecast\node_modules\mdns
> node-gyp rebuild

H:\dev\chromecast\node_modules\mdns>if not defined npm_config_node_gyp (node "C:\Users\gwilh\AppData\Roaming\nvm\v10.16.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\gwilh\AppData\Roaming\nvm\v10.16.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Génération des projets individuellement dans cette solution. Pour activer la génération en parallèle, ajoutez le commutateur "/m".
H:\dev\chromecast\node_modules\mdns\build\dns_sd_bindings.vcxproj(24,3): error MSB4019: Le projet importé "H:\Microsoft.Cpp.Default.props" est introuvable. Vérifiez que le chemin d'accès dans la déclaration
 <Import> est correct et que le fichier existe sur le disque.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\gwilh\AppData\Roaming\nvm\v10.16.0\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\gwilh\\AppData\\Roaming\\nvm\\v10.16.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd H:\dev\chromecast\node_modules\mdns
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN chromecast@1.0.0 No description
npm WARN chromecast@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdns@2.5.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mdns@2.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gwilh\AppData\Roaming\npm-cache\_logs\2019-11-14T19_44_04_919Z-debug.log                                                                        
`
note: H:\Microsoft.Cpp.Default.props does not exist in my disk

**Comment by 3l0w** [comment]
Ok i find something:
https://github.com/astro/node-expat/issues/189

I will test this tomorrow

**Comment by 3l0w** [comment]
I have test and that work !
