### ISSUE TITLE
Windows 7 Node v0.8.2 Build Fails

### ISSUE THREAD

**Issue by No9** [agnat/node_mdns#38]
Fresh install of 0.8.2 

```
npm http GET https://registry.npmjs.org/mdns
npm http 200 https://registry.npmjs.org/mdns

> mdns@0.0.7 install C:\Users\ANTON\node_modules\mdns
> node-gyp rebuild


C:\Users\ANTON\node_modules\mdns>node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
  txt_record_get_length.cpp
c:\users\anton\documents\github\node_mdns\src\mdns.hpp(15): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory [C:\Users\ANTON\Documents\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
  txt_record_buffer_to_object.cpp
c:\users\anton\documents\github\node_mdns\src\mdns.hpp(15): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory [C:\Users\ANTON\Documents\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
  dns_service_process_result.cpp
c:\users\anton\documents\github\node_mdns\src\mdns.hpp(15): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory [C:\Users\ANTON\Documents\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
  txt_record_deallocate.cpp
c:\users\anton\documents\github\node_mdns\src\mdns.hpp(15): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory [C:\Users\ANTON\Documents\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
  dns_service_browse.cpp
c:\users\anton\documents\github\node_mdns\src\mdns.hpp(15): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory [C:\Users\ANTON\Documents\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
  dns_service_enumerate_domains.cpp
c:\users\anton\documents\github\node_mdns\src\mdns.hpp(15): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory [C:\Users\ANTON\Documents\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
  dns_service_register.cpp
c:\users\anton\documents\github\node_mdns\src\mdns.hpp(15): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory [C:\Users\ANTON\Documents\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
  dns_service_ref_sock_fd.cpp
c:\users\anton\documents\github\node_mdns\src\mdns.hpp(15): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory [C:\Users\ANTON\Documents\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
  dns_service_resolve.cpp
c:\users\anton\documents\github\node_mdns\src\mdns.hpp(15): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory [C:\Users\ANTON\Documents\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
  mdns_utils.cpp
c:\users\anton\documents\github\node_mdns\src\mdns.hpp(15): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory [C:\Users\ANTON\Documents\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
  dns_service_ref.cpp
c:\users\anton\documents\github\node_mdns\src\mdns.hpp(15): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory [C:\Users\ANTON\Documents\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
  winsock_watcher.cpp
c:\users\anton\documents\github\node_mdns\src\mdns.hpp(15): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory [C:\Users\ANTON\Documents\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
  txt_record_ref.cpp
c:\users\anton\documents\github\node_mdns\src\mdns.hpp(15): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory [C:\Users\ANTON\Documents\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
  dns_service_ref_deallocate.cpp
c:\users\anton\documents\github\node_mdns\src\mdns.hpp(15): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory [C:\Users\ANTON\Documents\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
  txt_record_set_value.cpp
c:\users\anton\documents\github\node_mdns\src\mdns.hpp(15): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory [C:\Users\ANTON\Documents\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
  txt_record_create.cpp
c:\users\anton\documents\github\node_mdns\src\mdns.hpp(15): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory [C:\Users\ANTON\Documents\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
  dns_service_get_addr_info.cpp
c:\users\anton\documents\github\node_mdns\src\mdns.hpp(15): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory [C:\Users\ANTON\Documents\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
  dns_sd.cpp
c:\users\anton\documents\github\node_mdns\src\mdns.hpp(15): fatal error C1083: Cannot open include file: 'dns_sd.h': No such file or directory [C:\Users\ANTON\Documents\GitHub\node_mdns\build\dns_sd_bindings.vcxproj]
  Generating Code...
gyp ERR! rebuild error Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! rebuild error     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:214:23)
gyp ERR! rebuild error     at ChildProcess.EventEmitter.emit (events.js:91:17)
gyp ERR! rebuild error     at Process._handle.onexit (child_process.js:674:10)
gyp ERR! not ok
npm ERR! mdns@0.0.7 install: `node-gyp rebuild`
npm ERR! `cmd "/c" "node-gyp rebuild"` failed with 1
npm ERR!
npm ERR! Failed at the mdns@0.0.7 install script.
npm ERR! This is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "link"
npm ERR! cwd C:\Users\ANTON\Documents\GitHub\node_mdns
npm ERR! node -v v0.8.2
npm ERR! npm -v 1.1.36
npm ERR! code ELIFECYCLE
npm ERR! message mdns@0.0.7 install: `node-gyp rebuild`
npm ERR! message `cmd "/c" "node-gyp rebuild"` failed with 1
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\ANTON\Documents\GitHub\node_mdns\npm-debug.log
npm ERR! not ok code 0
```

**Comment by qdk0901** [comment]
still report missing "dns_sd.h" error when built under windows 8.1

**Comment by agnat** [comment]
Please see the [section on installation](https://github.com/agnat/node_mdns/blob/master/README.md) in the README.
