### ISSUE TITLE
Error: Symbol dns_sd_bindings_module not found.

### ISSUE THREAD

**Issue by jenil** [agnat/node_mdns#80]
I'm getting this error:

`````` /Users/jenil/../node_modules/mdns/lib/dns_sd.js:35
    throw ex;
          ^
Error: Symbol dns_sd_bindings_module not found.
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/jenil/../node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)```
``````

**Comment by mizyanlu** [comment]
got the same error too on  v0.10.45, working on it.

**Comment by zyanlu** [comment]
Everything  works well with dynamic link under ubuntu14 . and I believe you were trying to cross-compile node_mdns into other platforms.
The problem is for some reason you must **static** link libdns_sd.a  ,libavahi-common.a ,libavahi-client.a into dns_sd_bindings.node. cross-compiled binary doesn't  load libdns_sd.so properly (and didn't show up the right error msg).

**Comment by sunjunlishi** [comment]
me too,the problem,any one resolve it
